## KSETA Topical Courses
### GPU Computing with PyTorch - High Performance Computing at KIT
----

#### Part 1 - Getting to Know PyTorch

PyTorch is tensor computation library originally designed 

In [1]:
import torch
torch.__version__

'1.8.0.dev20210208+cu110'

Let us first create a vector from some user-defined data first.

In [2]:
vector = torch.tensor([0.0, 1.0, -1.0, 3.0])
vector

tensor([ 0.,  1., -1.,  3.])

It is also possible to initialize matrices, volumes and higher order tensors. Below you will find a two-dimensional, i.e. matrix, tensor example.

In [3]:
matrix = torch.tensor([
    [1, 2, 3],
    [6, 5, 4]
])
matrix

tensor([[1, 2, 3],
        [6, 5, 4]])

PyTorch provides several functions to streamline tensor initialization. It is for example possible to create tensors with uninitialized memory, filled with constant values or random data.

In [4]:
random_volume = torch.randn(size=(3, 4, 5))
random_volume

tensor([[[ 0.9005, -0.2420, -0.0477,  0.0413, -2.5220],
         [ 0.0699,  0.8276, -0.9583, -0.9358,  1.6107],
         [ 0.0247,  0.5094, -0.7615,  0.4949, -0.4701],
         [-0.1344,  0.6717, -0.7857,  1.6455,  2.6537]],

        [[ 1.3203,  0.2742,  1.7353,  0.0259,  0.3806],
         [-0.7005, -1.6252,  0.6543,  1.0404, -0.5003],
         [ 0.5825,  1.4406, -0.5091,  0.7830,  0.5318],
         [-1.4417, -0.4824,  1.3070, -1.5806, -0.5694]],

        [[ 0.8968,  1.0666,  1.3685, -0.5930, -0.3702],
         [-1.4366,  0.3959,  0.5588,  0.0815,  0.0174],
         [ 0.2306, -0.4699, -0.0595, -0.3242,  0.1430],
         [-0.8287,  1.0745,  1.6998, -1.1378,  0.8554]]])

Each PyTorch tensor has metadata associated with it that cannot only be queried, but also be modified in various calls. Some of the most commonly used metadata are a tensors `shape`, i.e. its dimensions, its `dtype`, i.e. the datatype of the elements, as well as the `device`, i.e. the processing device it is allocated on.

In [5]:
random_volume.shape, random_volume.dtype, random_volume.device

(torch.Size([3, 4, 5]), torch.float32, device(type='cpu'))

In [6]:
matrix.shape, matrix.dtype, matrix.device

(torch.Size([2, 3]), torch.int64, device(type='cpu'))

The metadata values can also be manipulated, e.g. by changing the datatype or adjusting the shape. In the following code snippet, we change the dimensionality of a one-dimensional vector into a two dimensional matrix.

In [7]:
vector = torch.arange(10)
vector.reshape(5, 2)

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

**Task 1:** try creating a tensor of data with the following dimensions `(100, 2, 2, 3)` and fill it with uniformly distributed `float64` values. Make use of PyTorch's `rand()` function for this.

In [8]:
a = torch.rand(size=(100, 2, 2, 3), dtype=torch.float64)
a

tensor([[[[0.4779, 0.8963, 0.1564],
          [0.9252, 0.2983, 0.8133]],

         [[0.9342, 0.3185, 0.2259],
          [0.6049, 0.2259, 0.5772]]],


        [[[0.7891, 0.5376, 0.9887],
          [0.6519, 0.1984, 0.2833]],

         [[0.4949, 0.0753, 0.1490],
          [0.7246, 0.2172, 0.8908]]],


        [[[0.7072, 0.6258, 0.5013],
          [0.9400, 0.8268, 0.3562]],

         [[0.9671, 0.4080, 0.5342],
          [0.4005, 0.1855, 0.6569]]],


        ...,


        [[[0.2861, 0.9914, 0.6111],
          [0.4929, 0.2340, 0.2239]],

         [[0.0257, 0.8508, 0.9453],
          [0.6065, 0.9971, 0.4881]]],


        [[[0.7435, 0.5496, 0.4005],
          [0.6093, 0.0333, 0.7664]],

         [[0.0948, 0.1662, 0.6652],
          [0.7743, 0.4131, 0.3896]]],


        [[[0.9662, 0.0760, 0.1183],
          [0.6538, 0.1959, 0.5469]],

         [[0.1809, 0.2175, 0.1672],
          [0.1814, 0.4961, 0.9050]]]], dtype=torch.float64)

----
#### Part 2 - Operations and Equations

PyTorch supports several dozens of tensor operations, including transposing, indexing, slicing, mathematical operations, linear algebra, and more. In the following examples we will have a brief look at them.

In [9]:
masses = torch.arange(10, dtype=torch.float32)
masses

tensor([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

We can add two vectors of same length, resulting in a element-wise operation of the individual vector elements.

In [10]:
ones = torch.ones(size=(10,))
masses + ones

tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

**Slicing** allows us to index only parts of the data and continue working with it. The used indices are zero-based, left-inclusive and right-exclusive.

In [11]:
masses[3:5]

tensor([3., 4.])

We can also formulate conditions, resulting in a boolean mask, which we can use to index data as demonstrated below.

In [12]:
masses > 7, masses[masses > 7]

(tensor([False, False, False, False, False, False, False, False,  True,  True]),
 tensor([8., 9.]))

Vectors, matrices, volumes and so forth can also be combined with **scalars**. In this case the scalar in applied element-wise to each tensor element. Let us calculate Earth's gravitational force at ground-level for the previously defined masses.

In [13]:
gravitational_force = masses * 9.81
gravitational_force

tensor([ 0.0000,  9.8100, 19.6200, 29.4300, 39.2400, 49.0500, 58.8600, 68.6700,
        78.4800, 88.2900])

PyTorch generally repeats operands if their shapes match, i.e. they have the same exact same dimension or the dimension is equal to one. This approach is called **broadcasting**.

In [14]:
broadcast = torch.ones(size=(3, 10)) + masses
broadcast

tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
        [ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
        [ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]])

PyTorch also provides reduction operations that reduce entire tensors or subsets, e.g. columns or row, to singular values. Commonly used reduction operations are `min()`, `max()` or `sum()` for example. Let us have a look at an example:

In [15]:
broadcast.sum(dim=0)

tensor([ 3.,  6.,  9., 12., 15., 18., 21., 24., 27., 30.])

Equally higher level operations are available like computing norms, matrix decompositions, or matrix multiplication.

In [16]:
torch.arange(10) @ torch.arange(10)

tensor(285)

**Task 2:** calculate mean and standard deviation along the first dimension for a normal-distributed data of dimensions `(100, 3)` 

In [17]:
data = torch.randn(size=(100, 3))

mean = (1.0 / data.shape[0]) * data.sum(dim=0)
stddev = (1.0 / data.shape[0] * (data - mean) ** 2).sum(dim=0).sqrt()

mean, stddev

(tensor([-0.1332, -0.0706,  0.0398]), tensor([0.9320, 0.9582, 1.1153]))

----
#### Part 3 - Using the GPU

PyTorch enables you to leverage GPUs to accelerate computations. Particularly well suited-are numerical problems, e.g. linear algebra, with identical operations. Let us get to know PyTorch's `.cuda` submodule a little. First, we should make sure that PyTorch has been properly loaded and initialized the software, here: CUDA, to interact with GPUs.

In [18]:
torch.cuda.is_available()

True

Everything seems to be in order. CUDA is available to PyTorch. Let us know check how many and what kind of GPUs we can use:

In [19]:
torch.cuda.device_count(), torch.cuda.get_device_name()

(1, 'A100-SXM4-40GB')

Let us now create a vector of data and move it from CPU to GPU.

In [20]:
m = torch.arange(10)
m

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Let us manually move the data to the GPU now.

In [21]:
m_gpu = m.cuda()
m_gpu

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], device='cuda:0')

Analogous to our previous usage of PyTorch, we can now GPU-accelerate computation by using the exact same interface.

In [22]:
m_gpu.sum()

tensor(45, device='cuda:0')

PyTorch's library call that make it necessary that the data resides in the CPU's main memory, e.g. printing out values, move data automatically around. Yet, we can also do so manually.

In [23]:
m_gpu.cpu().device

device(type='cpu')

PyTorch offers several other ways of initializing data directly on the GPU. Below you will find the most common approaches.

In [24]:
torch.arange(2, device='cuda')

tensor([0, 1], device='cuda:0')

In [25]:
torch.cuda.FloatTensor([1.0, 2.0])

tensor([1., 2.], device='cuda:0')

In [26]:
torch.set_default_tensor_type('torch.cuda.FloatTensor')
torch.randn(5).device

device(type='cuda', index=0)

Mixing devices is not possible and will result in an error.

In [27]:
torch.arange(10, device='cuda') + torch.arange(10, device='cpu')

RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!

**Task 3:** we can now put all introduced elements together to make actual meaningful computations. For the following example, we load particle decays, simulated using the `phasespace` Python package, from disk and subsequently use PyTorch to compute the *thrust* for each event. The thrust is defined as:

$$T=\max\limits_{\vec{n}}\frac{\sum_j |\vec{p}_j\cdot\vec{n}|}{\sum_j |\vec{p}_j|}$$

Where $\vec{p}_j$ are the particles' momenta and $\vec{n}$ a vector with norm 1. The vector $\vec{n}_T$ that maximizes the thrust is called the *thrust axis*. A thrust of $T\approx\frac{1}{2}$ implies a spherical momenta distribution, where as $T\approx 1$ indicates strong jets.

Let us download the data first.

In [44]:
import util
decays = util.download_data()
decays.shape, decays.device

(torch.Size([50000000, 6, 3]), device(type='cpu'))

In this example we have fifty million events, each consisting out of six final-state particles and their three x-, y- and z-momenta. According the formula above we will compute their thrust on the CPU first.

In [48]:
def compute_thrust(events):
    # simplified candidate estimation for n as average of particles
    n = events.sum(dim=1)
    # normalize n to be a unit vector
    n_norms = torch.linalg.norm(n, dim=1, keepdim=True)
    n /= n_norms
    
    # calculate both fraction components
    nominator = torch.bmm(events, n.unsqueeze(dim=2)).sum(dim=(1, 2))
    denominator = torch.linalg.norm(events, dim=2).sum(dim=1)
    
    # calculate thrust
    thrust = nominator / denominator
    
    return thrust

In [46]:
%%time
thrust = compute_thrust(decays)
thrust.min(), thrust.max()

CPU times: user 8min 28s, sys: 7.75 s, total: 8min 35s
Wall time: 15.4 s


(tensor(0.8072), tensor(0.9632))

In [47]:
%%time
thrust = compute_thrust(decays.cuda())
thrust.min(), thrust.max()

CPU times: user 325 ms, sys: 117 ms, total: 442 ms
Wall time: 441 ms


(tensor(0.8072, device='cuda:0'), tensor(0.9632, device='cuda:0'))